### ISSUE TITLE
Move all feature requests in OctoPrint to discussions?

### ISSUE THREAD

**Issue by foosel** [OctoPrint/meta#1]
We are currently still using the issue tracker for all feature requests in OctoPrint. However, since OctoPrint got started, GitHub added the Discussions feature, and given that that also supports upvoting it makes sense to utilize it for requests in OctoPrint. 

For a while I planned to move requests to the community forum, but that would have the downside of no assigned ticket IDs and thus having to open a ticket still for planned implementations and to reference in PRs. Having feature requests (and ONLY feature requests) live in OctoPrint's discussions would solve this.

**Comment by foosel** [comment]
After testing this out just now, I see two issues with this approach:

- No forms anymore. Issue forms are issue forms, not discussion forms, so we can no longer enforce the request form, which could mean a reduction in quality of feature requests again.
- No tracking in projects possible. In order to make a discussion trackable (again), it first needs to be converted into an issue. It could be possible to turn this into a kind of workflow - planning implementation of a request for a release could then mean converting it to an issue first, then tagging with the milestone. An unsolved question is how to handle up-for-grabs in this regard, especially in case of grabbed issues that then get abandoned before a solution is merged.

So, there needs to be some more thinking about how to actually implement that as a workflow before it can be done. If it should actually be done.

I'd be very interested in some thoughts here.

**Comment by foosel** [comment]
For reference see OctoPrint/OctoPrint#4545 that got converted to a discussion as OctoPrint/OctoPrint#4546 (currently 404 as I disabled discussions again for the time being):

![image](https://user-images.githubusercontent.com/83657/174638773-98b6c270-02c1-4787-9c06-c6d889e7a392.png)

**Comment by cp2004** [comment]
There is *kinda* supports upvoting for issues, or at least with the 👍 reaction? I know [MUI](https://github.com/mui/material-ui/issues) uses this kind of system, [encouraging users to upvote features like this](https://mui.com/x/react-data-grid/selection/#range-selection). You can sort by reactions quite easily - https://github.com/OctoPrint/OctoPrint/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc. It's nowhere near as explicit as discussions though.

Currently I'm generally unconvinced that moving feature requests to discussions will bring any real benefit with it. OctoPrint doesn't have a very large amount of issues to try and deal with really, 250 open things and I think there's definitely a few could be closed as 'not planned'. Discussions seems to me (from looking at how many other repositories use it) where user-support type questions are directed, and for that we already have enough places to look. There's no way to 'close' a discussion to remove them from any list once implemented or rejected (plugin exists, support req., anything).

**Comment by cp2004** [comment]
I do quite like https://github.com/orgs/OctoPrint/projects/6 though

**Comment by foosel** [comment]
> There's no way to 'close' a discussion to remove them from any list once implemented or rejected (plugin exists, support req., anything).

That's a *VERY* good point that I completely overlooked, so thanks for that. That pretty much makes this dead in the water now.

> I do quite like https://github.com/orgs/OctoPrint/projects/6 though

Had been meaning to do that for a while, finally did it. Part of my ongoing quest to make everything more transparent and easier to ask for help/make tasks more discoverable.

**Comment by foosel** [comment]
Going to consider this idea abandoned for now given the things that currently speak against it. Big thanks for the feedback!
