### ISSUE TITLE
Migrate actions to new output/state environment variables

### ISSUE THREAD

**Issue by foosel** [OctoPrint/meta#6]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

`::set-output` will cease to work in June 2023. All actions in OctoPrint's repos currently using that mechanism need to be changed over to the new environment variable based mechanism.

See [this search](https://github.com/search?q=org%3AOctoPrint+%3A%3Aset-output&type=code).

**Comment by max246** [comment]
Made a quick PR here: https://github.com/OctoPrint/actions/pull/1

**Comment by foosel** [comment]
Got rid of the rest under my control. Search seems to need some time to update, but should be clean now.
